from distutils.core import setup

setup(author="David Fillmore",
      author_email="marvin@frobnitz.co.uk",
      description="A Blorb-capable Z-Machine interpreter.",
      name="Viola",
      version="0.7.9",
      url="http://www.plover.net/~marvin/viola",
      scripts=['viola'],
      py_modules=[ 'blorb',
                   'header',
                   'io',
                   'numbers',
                   'output', 
                   'text',
                   'dictionary',
                   'iff', 
                   'objects',
                   'quetzal', 
                   'sounds',
                   'error',  
                   'input',
                   'memory',
                   'opcodes',
                   'routines',
                   'settings',
                   'game',
                   'instructions',
                   'optables',
                   'screen',
		   'babel'
		   ])
