glk_main

glk_select

glk_exit

glk_set_interrupt_handler

glk_select_poll

glk_tick

glk_window_struct
glk_stream_struct
glk_fileref_struct
glk_schannel_struct

glk_window_iterate
glk_stream_iterate
glk_fileref_iterate

glk_gestalt

glk_gestalt_ext

glk_buffer_to_lower_case_uni
glk_buffer_to_upper_case_uni 
glk_buffer_to_title_case_uni 
glk_put_char_uni
glk_put_string_uni
glk_put_buffer_uni 
glk_put_char_stream_uni
glk_put_string_stream_uni
glk_put_buffer_stream_uni
glk_get_char_stream_uni
glk_get_buffer_stream_uni
glk_get_line_stream_uni
glk_request_char_event_uni
glk_request_line_event_uni 
glk_stream_open_file_uni
glk_stream_open_memory_uni





